#!/bin/bash

wpad_view='"server": ['
wcps_view='"server": ['

for s in `cat ps.list`; do 
    wpad_view=$wpad_view'"'$s'",'
    
    wcps_view=$wcps_view'("'$s'",1),'
    
    wpad2_view=$wpad2_view'"PROXY '$s':3128",#'
    
    ns_view=$ns_view'CLIENT.IP.SRC.EQ('$s') || '
done

wpad_view=${wpad_view%?}']'
wcps_view=${wcps_view%?}']'
ns_view=$ns_view" CLIENT.IP.SRC.EQ(46.165.250.169) || CLIENT.IP.SRC.EQ(46.165.250.170) || CLIENT.IP.SRC.EQ(46.165.250.171) || CLIENT.IP.SRC.EQ(95.211.231.154) || CLIENT.IP.SRC.EQ(95.211.231.155) || CLIENT.IP.SRC.EQ(95.211.198.44) || CLIENT.IP.SRC.EQ(5.79.79.41) || CLIENT.IP.SRC.EQ(5.79.79.42) || CLIENT.IP.SRC.EQ(144.76.104.34)"

echo "*wpad view"
echo $wpad_view

echo ""

echo "*wcps view"
echo $wcps_view

echo ""

echo "*wpad2 view"
echo $wpad2_view | tr -s "#" "\n"

echo ""

echo "*ns view"
echo $ns_view
